"""
DocString
Python = Linguagem de programação
Tipo de tipagem = Dinâmica / Forte
str -> string -> texto
Strings são textos que estão dentro de aspas
"""
print(1234)

# Aspas simples
print('Cleberson Rodrigues')
print( 1,'Cleberson "Rodrigues"')
print( 2,"Cleberson 'Rodrigues'")



# Aspas duplas
print("Cleberson Rodrigues")



# Escape
print("Cleberson \"Rodrigues\"")


# r
print(r"Cleberson \"Rodrigues\"")

